# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.
version: '3.4'

services:
  Blazor-Docker-Test:
    image: Blazor-Docker-Test
    build:
      context: .
      dockerfile: Blazor-Docker-Test/Server/Dockerfile
    volumes:
      - /app/app_vol:/root/.aspnet/DataProtection-Keys
    ports:
        - 6080:80
        - 6443:443